export const BACKEND_URL = `https://charlesfrye--qart-api.modal.run`;

export const QR_CODE_DIMENSIONS = 768;

export const PLACEHOLDER_IMAGE_URL = `https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/okami-amaterasu-two-milford-martin.jpg`;

export const LOADING_MESSAGES = [
  `Compositing QR code...`,
  `"Quick Response" more like "Slow Response"...`,
  `Generating image...`,
  `Diffusing...`,
  `Cold booting (brr)...`,
  `Evading safety filters...`,
  `Reticulating splines...`,
  `Denoising latents...`,
  `Competing for attention...`,
  `Literally just vibing...`,
  `Making ES6 Promises we can't keep...`,
  `Mining XMR in your browser...`,
  `Fiddling with hyperparameters...`,
  `Deserializing data so we can serialize it again...`,
  `Looking up which way KL Divergence goes...`,
  `Logging user data to Grafana "on accident"...`,
  `Violating GDPR and Geneva Conventions...`,
  `Scrolling through the terms of service...`,
  `Publishing in ICQR...`,
  `Hugging some faces...`,
  `Synthesizing aesthetics...`,
  `Inventing new colors...`,
  `Rewriting the codebase with ChatGPT...`,
  `Rewriting the codebase with Claude...`,
  `Rewriting the codebase with Copilot...`,
  `Whispering to the bits and bytes...`,
  `Rolling out with the Transformers...`,
  `Taking a GANder...`,
  `Praying to RNGsus...`,
  `Torching a pie...`,
  `Consulting the AI Constitution...`,
  `Taming shoggoths...`,
  `Descending gradients...`,
  `Approximating Hessians...`,
  `Violating copyrights and droits moraux...`,
  `Tuning our LLaMAs...`,
  `Pushing directly to main...`,
  `Sorry, as an AI model, I cannot...`,
  `Racking up egress charges...`,
  `Provisioning infrastructure...`,
  `Finding product-market fit...`,
  `Waiting for lower interest rates...`,
  `Diluting equity...`,
  `Spinning up yet another Redis cache...`,
  `Editing some YAML...`,
  `Installing CUDA again...`,
  `Debiasing logits...`,
  `Composing induction heads...`,
  `Rewriting it in Rust...`,
  `Waiting for AWS to release more GPUs...`,
  `Waiting for GCP to release more GPUs...`,
  `Waiting for OCI to release more GPUs...`,
  `Waiting for Azure to release more GPUs...`,
  `Purchasing more NVIDIA stock...`,
  `Rewriting models in JAX...`,
  `Converting boomercore models from Keras...`,
  `Casting to int3...`,
  `Aligning models to human preferences...`,
  `Constructing data flywheel...`,
  `Writing SQL queries...`,
  `Promising C-suite we have an AI strategy...`,
  `Engineering prompts...`,
  `Doomscrolling...`,
  `Pivoting to video...`,
  `Unvanishing gradients...`,
  `Embedding embeddings...`,
  `Cross-validating...`,
  `Interpolating...`,
  `Following the manifold...`,
  `Extracting features...`,
  `Shopping at the feature store...`,
  `Driving a forklift in the data warehouse...`,
  `Waiting for an all_gather...`,
  `Masking your attention...`,
  `Detaching gradients...`,
  `Dropping out...`,
  `Staring at loss curves...`,
  `Doing alchemy...`,
  `Refactoring spaghetti...`,
  `Overfitting...`,
  `Underfitting...`,
  `Maximizing benchmarks...`,
  `Cherry-picking...`,
  `Converting to paper clips...`,
  `Scaling up to exa-FLOPs...`,
  `Analyzing principal components...`,
  `Solving the credit assignment problem...`,
  `Rectifiying all linear units...`,
  `Clipping gradients...`,
  `Normalizing batches...`,
  `Stealing from the stats department...`,
  `Awaiting async functions...`,
  `Padding, striding, and pooling...`,
  `Trading off bias and variance...`,
  `Buffering...`,
  `Invalidating caches...`,
  `Leveraging synergies...`,
  `Hiring more MLEs...`,
  `Quantizing...`,
  `Parroting...`,
  `Reducing perplexity...`,
  `Moving to Miami...`,
  `Seeking funding...`,
  `Pivoting to crypto...`,
  `Minting non-fungible tokens...`,
  `Updating DNS...`,
  `Downloading more RAM...`,
  `Downloading more VRAM...`,
  `Orthogonalizing foundation models...`,
  `Riding a LLaMA...`,
  `Comparing Mistral with Sirocco...`,
  `It's so over...`,
  `We're so back...`,
  `Checking for consistent candor...`,
  `Launching CUDA kernels...`,
  `Spinlocking...`,
  `Upgrading to Pydantic 2...`,
  `Downgrading to Pydantic 1...`,
  `Cleaning dirty RAGs...`,
  `Compacting...`,
  `Flushing the WAL...`,
  `Running torch.compile...`,
  `Achieving AGI internally...`,
  `Capturing regulators...`,
  `Leaking weights via torrent...`,
  `Asking Emad for more GPUs...`,
  `Restarting from checkpoint...`,
  `Invalidating Redis cache...`,
  `Downloading Postgres extension...`,
  `Compiling SQL queries...`,
  `YOUR AD HERE...`,
  `Rewriting it in Go...`,
  `Rewriting it in Zig...`,
  `Rewriting it in Hare...`,
  `Rewriting it in Haskell...`,
  `Going back to C++...`,
  `Fighting the borrow checker...`,
  `ERROR: CUDA_HOME is not set, bruh...`,
  `Definitely not training on books3...`,
  `Hot-swapping LoRAs...`,
  `The Golden Gate Bridge is an iconic...`,
  `Injecting prompts...`,
  `Ignoring previous instructions...`,
  `Deploying MLOps...`,
  `Deploying LLMOps...`,
  `Deploying AgentOps...`,
  `Switching from LangChain to llamaindex...`,
  `Switching from llamaindex to LangChain...`,
  `Reincorporating as a non-profit...`,
  `Switching from terraform to pulumi...`,
  `Switching from pulumi to raw k8s...`,
  `Switching from raw k8s to terraform...`,
  `Compiling prompts with DSPy...`,
  `Running Monte Carlo Tree Search...`,
  `Waiting on Netlify deployment...`,
  `Waiting on Vercel deployment...`,
  `Migrating to SQLite...`,
  `Migrating to duckdb...`,
  `Grinding more LeetCode...`,
  `Asking for help on weird Discords...`,
  `Asking for help on weird subreddits...`,
  `Boosting LMSys ELO...`,
  `Delving into fascinating topics...`,
  `Scaling up vibe checks...`,
  `Running LGTM@10 benchmark...`,
  `Switching from Devin to Windsurf...`,
  `Switching from Windsurf to Cursor...`,
  `Switching from Cursor to Devin...`,
  `Switching from OpenAI to Claude...`,
  `Switching from Claude to DeepSeek...`,
  `Switching from DeepSeek to Gemini...`,
  `Switching from Gemini to OpenAI...`,
  `Learning from unverifiable rewards...`,
  `Learning from verifiable rewards...`,
  `Scaling large language monkeys...`,
  `Trickling ICE candidates...`,
  `Performing STUN rendezvous...`,
  `Bypassing kernel...`,
  `Getting off to a RoCE start...`,
  `Spending a band on InfiniBand...`,
  `... boop`,
  `Inserting em dashes—carefully...`,
  `Raising $1bn seed...`,
  `Negotiating OpenAI acquihire...`,
  `Negotiating equity-for-compute...`,
  `Quantizing to fp8...`,
  `Quantizing to fp4...`,
  `Quantizing to int8...`,
  `Quantizing to int4...`,
  `Quantizing to int3...`,
  `Quantizing to 1.58bit...`,
  `Quantizing to fp0...`,
  `Rewriting it in Modular...`,
  `Building out data centers...`,
  `Switching from air cooling to liquid...`,
  `Switching from liquid cooling to air...`,
  `Rewriting for Ampere...`,
  `Rewriting for Hopper...`,
  `Rewriting for Blackwell...`,
  `Rewriting for Vera Rubin...`,
  `thonking...`,
  `Waiting out a GCP outage...`,
  `Waiting out an AWS outage...`,
  `Waiting out an OCI outage...`,
  `Waiting out an Azure outage...`,
  `200 more like 💯 mirite...`,
  `Disaggregating prefill and decode...`,
  `Switching from vLLM to SGLang...`,
  `Switching from SGLang to TensorRT-LLM...`,
  `Switching from TensorRT-LLM to vLLM...`,
  `Launching the missiles...`,
  `Maximizing throughput...`,
  `Minimizing latency...`,
  `Settling the Pareto frontier...`,
];

export const LOADING_MESSAGE_INTERVAL_MS = 3000;
