export const BACKEND_URL = `https://charlesfrye--qart-api.modal.run`;

export const PLACEHOLDER_IMAGE_URL = `https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/okami-amaterasu-two-milford-martin.jpg`;

export const LOADING_MESSAGES = [
  `Compositing QR code...`,
  `Generating image...`,
  `Diffusing (but stably)...`,
  `Cold booting (brr)...`,
  `Evading safety filters...`,
  `Reticulating splines...`,
  `Denoising latents...`,
  `Competing for attention...`,
  `Literally just vibing...`,
  `Making ES6 Promises we can't keep...`,
  `Mining XMR in your browser...`,
  `Fiddling with hyperparameters...`,
  `Deserializing data so we can serialize it again...`,
  `Looking up which way the KL Divergence goes...`,
  `Logging personal data to Grafana "on accident"...`,
  `Violating the GDPR and the Geneva Convention...`,
  `Scrolling through the terms of service...`,
  `Publishing in ICLR...`,
  `Hugging some faces...`,
  `Synthesizing aesthetics...`,
  `Inventing new colors...`,
  `Rewriting the codebase with ChatGPT...`,
  `Whispering to the bits and bytes...`,
  `Rolling out with the Transfomers...`,
  `Taking a GANder...`,
  `Rolling the art dice...`,
  `Torching a pie...`,
  `Consulting the AI Constitution...`,
  `Taming shoggoths...`,
  `Descending gradients...`,
  `Approximating Hessians...`,
  `Violating copyrights and droits moraux...`,
  `Tuning our LLaMAs...`,
  `Pushing directly to main...`,
  `As an AI model, I...`,
  `Racking up egress charges...`,
  `Provisioning infrastructure...`,
  `Finding product-market fit...`,
  `Waiting for lower interest rates...`,
  `Diluting equity...`,
  `Spinning up yet another Redis cache...`,
  `Editing some YAML...`,
  `Installing CUDA again...`,
  `Debiasing logits...`,
  `Composing induction heads...`,
  `Rewriting it in Rust...`,
  `Waiting for AWS to release more GPUs...`,
  `Purchasing more NVIDIA stock...`,
  `Rewriting models in JAX...`,
  `Converting boomercore models from Keras...`,
  `Casting to int3...`,
  `Aligning models to human preferences...`,
  `Constructing data flywheel...`,
  `Writing SQL queries...`,
  `Promising C-suite we have an AI strategy...`,
  `Engineering prompts...`,
  `Doomscrolling...`,
  `Pivoting to video...`,
  `Unvanishing gradients...`,
  `Embedding embeddings...`,
  `Cross-validating...`,
  `Interpolating...`,
  `Following the manifold...`,
  `Extracting features...`,
  `Shopping at the feature store...`,
  `Driving a forklift in the data warehouse...`,
  `Waiting for an all_gather...`,
  `Masking your attention...`,
  `Detaching gradients...`,
  `Dropping out...`,
  `Staring at loss curves...`,
  `Doing alchemy...`,
  `Refactoring spaghetti...`,
  `Overfitting...`,
  `Underfitting...`,
  `Maximizing benchmarks...`,
  `Cherry-picking...`,
  `Converting to paper clips...`,
  `Scaling up to exa-FLOPs...`,
  `Analyzing principal components...`,
  `Solving the credit assignment problem...`,
  `Rectifiying all linear units...`,
  `Clipping gradients...`,
  `Normalizing batches...`,
  `Stealing from the stats department...`,
  `Awaiting async functions...`,
  `Padding, striding, and pooling...`,
  `Trading off bias and variance...`,
  `Buffering...`,
  `Invalidating caches...`,
  `Leveraging synergies...`,
  `Hiring more MLEs...`,
  `Quantizing...`,
  `Parroting...`,
  `Reducing perplexity...`,
  `Moving to Miami...`,
  `Seeking funding...`,
  `Pivoting to crypto...`,
  `Minting non-fungible tokens...`,
  `Updating DNS...`,
  `Downloading more RAM...`,
  `Downloading more VRAM...`,
];

export const LOADING_MESSAGE_INTERVAL_MS = 5000;
